import "../../public/css/style.css";
import "../../public/css/responsive.css";
import "../../public/css/bootstrap.min.css";
import "../../public/css/animate.min.css";
import "../../public/css/magnific-popup.css";
import "../../public/fontawesome/css/all.min.css";
import "../../public/font-flaticon/flaticon.css";
import "../../public/css/dripicons.css";
import "../../public/css/slick.css";
import "../../public/css/meanmenu.css";
import "../../public/css/default.css";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>{children}</body>
    </html>
  );
}
